### ISSUE TITLE
Address some open issues at TheCreeperOfRedstone/RPG-Items-2

### ISSUE THREAD

**Issue by Artoria2e5** [NyaaCat/RPGitems-reloaded#54]
It appears that there are still a handful of open issues at TheCreeperOfRedstone/RPG-Items-2. It might be nice if NyaaCat can confirm these are fixed..

(just click on the checkbox if resolved)
- [ ] Clashes with GemManager (TheCreeperOfRedstone/RPG-Items-2#12)
- [ ] Using YAML configs to create weapon presets (TheCreeperOfRedstone/RPG-Items-2#10) 
  - See also #34.
- [ ] Max Health Power, Set-of-Armor Power (TheCreeperOfRedstone/RPG-Items-2#9)
  - See also #44.
- [ ] Permissions: what you can do with fooItem. (TheCreeperOfRedstone/RPG-Items-2#6)
- [ ] Permissions: whether you can have fooItem. (TheCreeperOfRedstone/RPG-Items-2#5)
- [x] Bug: custom durability doesn't work. (TheCreeperOfRedstone/RPG-Items-2#4)
- [ ] fooItem.minPlayerLevel: TheCreeperOfRedstone/RPG-Items-2#3
- [ ] Randomly give RPGitems when crafting usual things: TheCreeperOfRedstone/RPG-Items-2#2
